### ISSUE TITLE
Doesn't works

### ISSUE THREAD

**Issue by furkanimamoglu** [ray-xuanruilee/GA4_Measurement-Protocol_Python#1]
I tried as same but doesn't gives any hit on screen. also /mp/collect page not found.
Is there anything wrong?

**Comment by ray-xuanruilee** [comment]
Hi @furkanimamoglu, this still works for me _(see screenshot below with today's date)._

![image](https://user-images.githubusercontent.com/83920920/181415530-8d5f7291-388a-4f47-863f-015764b73f10.png)

Please double check against your GA4 Property:
1. You are using the correct Measurement ID _(starts with "G-XXX")_
2. You are using the right Measurement Protocol API Secret Key.

Cheers!
